version: 2.1

executors:
  maven-executor:
    docker:
      - image: circleci/openjdk:8-jdk
commands:
  configure-gpg:
    steps:
      - run:
          name: Configure GPG private key for signing project artifacts in OSS Sonatype
          command: |
            echo $SECRING_GPG_ASC_BASE64 | base64 --decode | gpg --batch --no-tty --import --yes
  restore-maven-cache:
    steps:
      - restore_cache:
          keys:
          - maven-m2-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
          - maven-m2-v1-{{ .Branch }}
          - maven-m2-v1
      - run:
          name: Retrieve all Maven plugins and dependencies
          command: |
            mvn  -s .circleci/maven-release-settings.xml -Prelease -Preporting -Pallow-snapshots --fail-never dependency:go-offline || true
  save-maven-cache:
    steps:
      - save_cache:
          paths:
            - ~/.m2
          key: maven-m2-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
jobs:
  build-and-test:
    executor: maven-executor
    steps:
      - checkout
      - restore-maven-cache
      - configure-gpg
      - run:
          name: Build and test Java code
          command: mvn -Prelease verify
      - save-maven-cache
      - persist_to_workspace:
          root: .
          paths:
            - .
      - store_artifacts:
          path: oss-build-support/target
          destination: artifacts/oss-build-support
      - store_artifacts:
          path: oss-parent/target
          destination: artifacts/oss-parent
  deploy-release:
    executor: maven-executor
    steps:
      - attach_workspace:
          at: .
      - restore-maven-cache
      - configure-gpg
      - run:
          name: Deploy new RELEASE to Maven Central
          command: |
            mvn -s .circleci/maven-release-settings.xml -Prelease deploy
            # mvn -s .circleci/maven-release-settings.xml -Prelease nexus-staging:close -DstagingDescription="closing to release"
      - save-maven-cache
  deploy-snapshot:
    executor: maven-executor
    steps:
      - attach_workspace:
          at: .
      - restore-maven-cache
      - configure-gpg
      - run:
          name: Deploy new SNAPSHOT to Maven Central
          command: |
            release_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
            if [[ $release_version == *-SNAPSHOT ]]; then
              mvn -s .circleci/maven-release-settings.xml -Prelease deploy
            fi
      - save-maven-cache
  deploy-site:
    executor: maven-executor
    steps:
      - attach_workspace:
          at: .
      - restore-maven-cache
      - run:
          name: Build Site with Maven
          command: |
            mvn -Preporting -Prelease package site site:stage
      - save-maven-cache
      - add_ssh_keys:
          fingerprints:
            - "b3:aa:a7:c5:bb:86:ad:14:bc:13:54:80:d1:79:18:1e"
      - run:
          name: Run deploy script
          command: |
            touch target/staging/.nojekyll
            mkdir target/staging/.circleci
            cp .circleci/config.yml target/staging/.circleci
            bash .circleci/deploy.sh --push-only -v -m "Deploying website [ci deploy skip]"
workflows:
  releases:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore: /.*/
            # only act on version tags
            tags:
              only: /v[0-9]+(\.[0-9]+)*.*/
      - deploy-release:
          requires:
            - build-and-test
          filters:
            branches:
              ignore: /.*/
            # only act on version tags
            tags:
              only: /v[0-9]+(\.[0-9]+)*.*/
      - deploy-site:
          requires:
            - deploy-release
          filters:
            branches:
              ignore: /.*/
            # only act on version tags
            tags:
              only: /v[0-9]+(\.[0-9]+)*.*/
  snapshots:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore: nist-pages
      - deploy-snapshot:
          requires:
          - build-and-test
          filters:
            branches:
              only: master
